version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
  
  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      PORT: 3000
      NATS_URL: nats://nats-server:4222

  products-ms:
    build: ./products
    volumes:
      - ./products/src:/usr/src/app/src
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      PORT: 3001
      NATS_URL: nats://nats-server:4222
      DATABASE_URL: file:./dev.db
  
  order-ms:
    depends_on:
      - "orderDb"
    build: ./order-ms
    volumes:
      - ./order-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      PORT: 3002
      NATS_URL: nats://nats-server:4222
      DATABASE_URL: postgres://postgres:postgres@orderDb:5432/orderdb?schema=public
  
  orderDb:
    image: postgres:16.2
    restart: always
    container_name: orderDb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    volumes:
      - ./order-ms/postgres-data:/var/lib/postgresql/data
